server {
    listen 80;
    server_name localhost;
    root /home/xolbek/Desktop/NT/NT4/Technical_tasks_library/tasks/tasklib;
    #root /home/xolbek/Desktop/NT/NT4/Technical_tasks_library/tasklib;
    index index.php;

    #location / {
    # try_files $uri $uri/ =404;
    #}
    
    location / {
        try_files $uri /index.php?$query_string;
    }

    location ~ \.php$ {
      #fastcgi_pass unix:/run/php/php8.3-fpm;  # PHP-FPM default socket
      fastcgi_pass unix:/run/php/php8.3-fpm.sock;
      fastcgi_index index.php;
      include fastcgi_params;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
